name: GitHub Actions Demo
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Start building project."
      - run: npm run build
      - run: ls
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Start deploying"
