name: GitHub Actions Demo
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Start building project."
      - run: ls
        uses: actions/checkout@v3
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Start deploying"
